### ISSUE TITLE
Massiv bug...

### ISSUE THREAD

**Issue by Wertzui123** [Seyz123/InventorySynchronizer#5]
When you are online on 2 servers, connected with this plugin and with the same name, you can just duplicate, because it just saves when you leave. It should save when ever you change your inventory, so that if you drop something on CB1, it'll disappear in the inventory on CB2.

**Comment by sowahq** [comment]
Actually, it's a pretty big bug, I'll fix it for the next update. Thank you for reporting the bug!

**Comment by Wertzui123** [comment]
Nice 👍

**Comment by Wertzui123** [comment]
Is it implemented?

**Comment by sowahq** [comment]
Next update
