### ISSUE TITLE
Plugin not up to date

### ISSUE THREAD

**Issue by JRKPirna** [Seyz123/InventorySynchronizer#6]
The plugin is actually not up to date and can't be used on the actual PMMP version. Hopefully you'll update soon we need this plugin.
Best regards.

**Comment by sowahq** [comment]
Everything is working fine on my end, are you sure you’ve set everything up right?

**Comment by JRKPirna** [comment]
Yeah, idk my partner setted it up and said that it aint working. I'll check it myself and test it again

**Comment by JRKPirna** [comment]
Yeah, idk my partner setted it up and said that it aint working. I'll check it myself and test it again

**Comment by JRKPirna** [comment]
actually he messed the mysql up. It's alright now 😄
